Repository RedisJSON/RedisJSON, pull requests merged in 2021-05, with the labels that each got.

#333 Backward RDB load of older versions with Search schema emedded
  src/lib.rs
  src/redisjson.rs
Labels: bug

#306 Add JSON.CLEAR command
  src/lib.rs
  src/redisjson.rs
  tests/pytest/test.py
Labels: enhancement

#350 Minimal Redis version support is 6
  ramp.yml
Labels: enhancement

#355 RedisJSON LOCAL/CI benchmarks on v1.0.*
  .circleci/config.yml
  Makefile
  src/Makefile
  tests/benchmarks/.gitignore
  tests/benchmarks/Readme.md
  tests/benchmarks/defaults.yml
  tests/benchmarks/json_arrappend_geojson.yml
  tests/benchmarks/json_get_ResultSet.totalResultsAvailable_jsonsl-yahoo2_json.yml
  tests/benchmarks/json_get_[0]_jsonsl-1.yml
  tests/benchmarks/json_get_[7]_jsonsl-1.yml
  tests/benchmarks/json_get_[8].zero_jsonsl-1.yml
  tests/benchmarks/json_get_[web-app].servlet[0][servlet-name]_json-parser-0000.yml
  tests/benchmarks/json_get_[web-app].servlet[0]_json-parser-0000.yml
  tests/benchmarks/json_get_[web-app].servlet_json-parser-0000.yml
  tests/benchmarks/json_get_array_of_docs[1]_pass_100_json.yml
  tests/benchmarks/json_get_array_of_docs[1]sclr_pass_100_json.yml
  tests/benchmarks/json_get_array_of_docs_pass_100_json.yml
  tests/benchmarks/json_get_fulldoc_json-parser-0000.yml
  tests/benchmarks/json_get_fulldoc_jsonsl-1.yml
  tests/benchmarks/json_get_fulldoc_jsonsl-yahoo2_json.yml
  tests/benchmarks/json_get_fulldoc_jsonsl-yelp_json.yml
  tests/benchmarks/json_get_fulldoc_pass_100_json.yml
  tests/benchmarks/json_get_key_empty.yml
  tests/benchmarks/json_get_message.code_jsonsl-yelp_json.yml
  tests/benchmarks/json_get_sclr_pass_100_json.yml
  tests/benchmarks/json_get_sub_doc.sclr_pass_100_json.yml
  tests/benchmarks/json_get_sub_doc_pass_100_json.yml
  tests/benchmarks/json_numincrby_num_1.yml
  tests/benchmarks/json_nummultby_num_1.yml
  tests/benchmarks/json_set_ResultSet.totalResultsAvailable_1_jsonsl-yahoo2_json.yml
  tests/benchmarks/json_set_[0]foo_jsonsl-1.yml
  tests/benchmarks/json_set_[web-app].servlet[0][servlet-name]_bar_json-parser-0000.yml
  tests/benchmarks/json_set_fulldoc_pass_100_json.yml
  tests/benchmarks/json_set_key_empty.yml
  tests/benchmarks/json_set_message.code_1_jsonsl-yelp_json.yml
  tests/benchmarks/json_set_num_0.yml
  tests/benchmarks/json_set_sclr_1_pass_100_json.yml
  tests/benchmarks/json_set_sclr_pass_100_json.yml
  tests/benchmarks/remote/install_deps.sh
  tests/benchmarks/requirements.txt
Labels: x:quality

#378 cherry pick: Included hset vs json comparison benchmark use-cases
  tests/benchmarks/json_vs_hashes_hset_key_simple.yml
  tests/benchmarks/json_vs_hashes_json.set_key_simple.yml
Labels: x:quality

#377 [add] Included hset vs json comparison benchmark use-cases
  tests/benchmarks/json_vs_hashes_hset_key_simple.yml
  tests/benchmarks/json_vs_hashes_json.set_key_simple.yml
Labels: x:quality
