Repository RedisJSON/RedisJSON, pull requests merged in 2021-04, with the labels that each got.

#283 Fix 404ing command anchors
  docs/index.md
Labels: documentation

#309 Fixed redismodule-rs crate version #
  Cargo.toml
Labels: enhancement

#312 update redismodule-rs to v0.14
  Cargo.lock
  Cargo.toml
Labels: enhancement

#307 RedisJSON LOCAL/CI benchmarks kickoff based on https://oss.redislabs.com/redisjson/performance/
  .circleci/config.yml
  Makefile
  tests/benchmarks/.gitignore
  tests/benchmarks/defaults.yml
  tests/benchmarks/json_arrappend_geojson.yml
  tests/benchmarks/json_get_ResultSet.totalResultsAvailable_jsonsl-yahoo2_json.yml
  tests/benchmarks/json_get_[0]_jsonsl-1.yml
  tests/benchmarks/json_get_[7]_jsonsl-1.yml
  tests/benchmarks/json_get_[8].zero_jsonsl-1.yml
  tests/benchmarks/json_get_[web-app].servlet[0][servlet-name]_json-parser-0000.yml
  tests/benchmarks/json_get_[web-app].servlet[0]_json-parser-0000.yml
  tests/benchmarks/json_get_[web-app].servlet_json-parser-0000.yml
  tests/benchmarks/json_get_array_of_docs[1]_pass_100_json.yml
  tests/benchmarks/json_get_array_of_docs[1]sclr_pass_100_json.yml
  tests/benchmarks/json_get_array_of_docs_pass_100_json.yml
  tests/benchmarks/json_get_fulldoc_json-parser-0000.yml
  tests/benchmarks/json_get_fulldoc_jsonsl-1.yml
  tests/benchmarks/json_get_fulldoc_jsonsl-yahoo2_json.yml
  tests/benchmarks/json_get_fulldoc_jsonsl-yelp_json.yml
  tests/benchmarks/json_get_fulldoc_pass_100_json.yml
  tests/benchmarks/json_get_key_empty.yml
  tests/benchmarks/json_get_message.code_jsonsl-yelp_json.yml
  tests/benchmarks/json_get_sclr_pass_100_json.yml
  tests/benchmarks/json_get_sub_doc.sclr_pass_100_json.yml
  tests/benchmarks/json_get_sub_doc_pass_100_json.yml
  tests/benchmarks/json_numincrby_num_1.yml
  tests/benchmarks/json_nummultby_num_2.yml
  tests/benchmarks/json_set_ResultSet.totalResultsAvailable_1_jsonsl-yahoo2_json.yml
  tests/benchmarks/json_set_[0]foo_jsonsl-1.yml
  tests/benchmarks/json_set_[web-app].servlet[0][servlet-name]_bar_json-parser-0000.yml
  tests/benchmarks/json_set_fulldoc_pass_100_json.yml
  tests/benchmarks/json_set_key_empty.yml
  tests/benchmarks/json_set_message.code_1_jsonsl-yelp_json.yml
  tests/benchmarks/json_set_num_0.yml
  tests/benchmarks/json_set_sclr_1_pass_100_json.yml
  tests/benchmarks/json_set_sclr_pass_100_json.yml
  tests/benchmarks/remote/install_deps.sh
  tests/benchmarks/requirements.txt
Labels: x:quality

#322 Running only performance automation on tags, master, and integration branches
  .circleci/config.yml
Labels: x:quality

#332 Update to Redis 6.2.2
  Dockerfile
Labels: enhancement

#324 Fix json.arrappend performance
  src/lib.rs
  src/redisjson.rs
  tests/pytest/test.py
Labels: bug
