Repository RedisJSON/RedisJSON, pull requests merged in 2022-12, with the labels that each got.

#878 Document clearly when filter regex match was introduced
  docs/docs/path.md
Labels: documentation

#888 Add run with docker
  docs/docs/_index.md
Labels: documentation

#885 [DOC UPDATE] Update return info in JSON.GET topics
  docs/commands/json.get.md
  docs/docs/path.md
Labels: documentation

#892 Allow JSON.ARRINDEX with none scalar values
  docs/commands/json.arrindex.md
  src/commands.rs
  tests/pytest/test.py
  tests/pytest/test_multi.py
Labels: enhancement

#896 Updated benchmark trigger by label action:run-benchmark and to run performance nightly only once a week
  .circleci/config.yml
  .github/workflows/trigger-benchmark.yml
Labels: action:run-benchmark

#898 update to the latest stable rust even if rust installed
  sbin/system-setup.py
Labels: action:run-benchmark
